import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://192.168.1.111:3000/');
  await page.getByPlaceholder('Enter Email').click();
  await page.getByPlaceholder('Enter Email').fill('admin');
  await page.getByPlaceholder('Enter Password').click();
  await page.getByPlaceholder('Enter Password').fill('admin');
  await page.getByRole('button', { name: 'Log In' }).click();
  await page.getByRole('link', { name: 'Configuration' }).click();
  await page.getByRole('button', { name: '+ Add Camera' }).click();
  await page.locator('div').filter({ hasText: /^192\.168\.1\.165$/ }).click();
  await page.getByPlaceholder('Username').click();
  await page.getByPlaceholder('Username').fill('admin');
  await page.getByPlaceholder('Password').click();
  await page.getByPlaceholder('Password').fill('just4Taqtile');
  await page.getByRole('button', { name: 'Connect' }).click();
  await page.getByText('Name: 192.168.1.165').click();
//   await page.getByLabel('Idle control').check();
//   await page.getByRole('button', { name: 'Done' }).click();
//   await page.waitForResponse(response => response.url() === 'http://192.168.1.111/api/algorithms/create-process/' && response.request().method() === 'POST');
//   expect(response.status()).toBe(200);
  await page.locator('div').filter({ hasText: /^Camera Name$/ }).getByRole('textbox').fill('testus');
  await page.getByRole('button', { name: 'Done' }).click();
  await page.getByRole('link', { name: 'Inventory' }).click();
  await page.getByRole('button', { name: 'Add item' }).click();
  await page.getByPlaceholder('Enter item name').click();
  await page.getByPlaceholder('Enter item name').fill('tests');
  await page.getByPlaceholder('Enter number').click();
  await page.getByPlaceholder('Enter number').fill('5');
  await page.locator('form svg').click();
  await page.locator('form svg').click();
  await page.getByRole('combobox', { name: 'Select a camera' }).selectOption('testus');
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.locator('.addInventoryModal_draw__kvnex').click();
  await page.getByRole('button', { name: 'Save' }).click();
//   await page.locator('td:nth-child(6)').first().click();
//   await page.getByText('Delete').click();
//   await page.getByRole('button', { name: 'Delete' }).click();
});